# Generated by Django 4.0.4 on 2022-04-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ticket_closed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
